name: Execute Jupyter Notebook

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  execute_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert pandas shap scikit-learn joblib  # Include any dependencies needed for the notebook

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute CSI5155 Assignment 2 - Kelvin Mock 300453668.ipynb

      - name: Upload executed notebook
        uses: actions/upload-artifact@v3
        with:
          name: executed-notebook
          path: executed_CSI5155 Assignment 2 - Kelvin Mock 300453668.ipynb.ipynb
